# Generated by Django 4.0.4 on 2022-05-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_alter_subscription_ended_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='posts', through='rareapi.PostTag', to='rareapi.tag'),
        ),
    ]
